export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500,
}

export const ERROR_CODE = {
  INTERNAL_SERVER_ERROR: 11000,
  CANNOT_CREATE_USER: 10001,
}

export const PAGINATION_SETTING = {
  DEFAULT_PAGE: 1,
  PAGE_SIZE: 10,
}
